"""empty message

Revision ID: 9aebba5f4f5b
Revises: 8ee20266bb5b
Create Date: 2021-03-05 16:43:26.122499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aebba5f4f5b'
down_revision = '8ee20266bb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_artistid_starttime', 'shows', ['artist_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_artistid_starttime', 'shows', type_='unique')
    # ### end Alembic commands ###
