"""empty message

Revision ID: e9f614a8dce6
Revises: 2d98d22dfbef
Create Date: 2021-02-28 05:23:44.254402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f614a8dce6'
down_revision = '2d98d22dfbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    op.add_column('artists', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('artists', sa.Column('modified_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('venues', sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('venues', sa.Column('modified_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'modified_time')
    op.drop_column('venues', 'created_time')
    op.drop_column('artists', 'modified_time')
    op.drop_column('artists', 'created_time')
    op.drop_table('shows')
    # ### end Alembic commands ###
